begin: "2000-01-01 00:00:00"
end: "2000-01-01 23:59:59"
log_file: sample_ble.csv
init_pos: [0, 0]
lost_tj_policy: 1
result_dir_name:

win_size: 2

beacon_dir: beacon
enable_clear_map: True
enable_draw_beacons: False
enable_save_img: False
enable_save_video: False
frame_rate: 1
map_conf_file: sample.yaml
map_img_file: sample.pgm
map_show_range:
win_stride: 1

truth_log_file:

enable_write_conf: False

win_policy: 1

# tentaion
map_show_policy: 3
direct_sd: 1
max_particle_stride: 25
rand_pos_range: 375
lost_resample_policy: 1
dist_sd: 37.5
el_correction: 2
estim_pos_policy: 2
neg_weight_coef: 0
propag_coef: 5
